language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
  - rbx-head
script: "bundle exec rspec spec"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
