language: ruby

cache: bundler

rvm:
  - 2.5.7
  - 2.6.5
  - jruby
  - rbx-2

gemfile:
  - gemfiles/sidekiq52_rails42.gemfile
  - gemfiles/sidekiq52_rails52.gemfile
  - gemfiles/sidekiq60_rails52.gemfile

script: "bundle exec rspec spec"

before_install:
  - gem install bundler:1.17.3

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
