language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - jruby
  - rbx-2
  
script: "bundle exec rspec spec"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  include:
    - rvm: 2.0
      gemfile: gemfiles/ruby20.gemfile
